### PR TITLE
Let's add Vivaldi browser...

### PR DESCRIPTION
**Pull request by FredBezies**
And its ffmpeg-codecs :)

### CODE REVIEW

**Comment by MatMoul** [comment]
`archdi -t FredBezies patch-9` doesn't work
`/archdi/install/apps/internet/webbrowser: ligne 33:     '"vivaldi-ffmpeg-codecs"') aurpkg="$aurpkg $(echo $itm | sed 's/"//g')";;'`
I'm searching the error...

**Comment by MatMoul** [comment]
Line 32 the ' after vivaldi

**Comment by FredBezies** [comment]
Could be a good idea to add also opera-ffmpeg-codecs (from community) in this list in order to be as complete as Vivaldi.

**Comment by MatMoul** [comment]
If the option isn't checked each user can made what he want...
But in this case, it can be good to add a small decsription on the second field of the list that explain why this package is here.

**Comment by MatMoul** [comment]
I've just merged theses last changes...
This the first time that I encouter this case and I don't have tag for this...
It seem this best to make a new PR when this one has the merged tag...

**Comment by MatMoul** [comment]
New release online...

**Pull request merged**
