### PR TITLE
feat: Added Gnome desktop support

### PR DESCRIPTION
**Pull request by kuohuanhuan**
Added Gnome ~

### CODE REVIEW

**Comment by kuohuanhuan** [comment]
Note:
Added Gnome desktop support
('Cause I'd like to use Gnome btw)

**Comment by kuohuanhuan** [comment]
Oh forgoted

@MatMoul

**Comment by kuohuanhuan** [comment]
Improved, all done.

**Comment by kuohuanhuan** [comment]
Ready for review.
@MatMoul

**Comment by kuohuanhuan** [comment]
@MatMoul

**Comment by MatMoul** [comment]
I'm trying to test your change with archdi -t kuohuanhuan develop without success...

Give me some times before accept or not this merge.

**Comment by kuohuanhuan** [comment]
Tested again, 
well... It doesn't work

**Pull request closed without merging**
