### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Arch-Lover**
i started to add gnome

### CODE REVIEW

**Comment by MatMoul** [comment]
Thank you for your PR ...
It's a good idea to have a lite version and also a minimal version of gnome but not with the "complement" file.
I suggest you look at the KDE-APPS menu in Plasma5 how and mainly this file : https://github.com/MatMoul/archdi-pkg/blob/master/install/desktop/plasma5/kdeapps/packages
In this file, you can set somefile On or OFF but if new file are include in the group, this will added to the menu.

Now we need to choose to menu layout :
A first solution where you choose the install type Full, Lite and then the two group are managed from the same install methos :
Install - Desktop Environement - Gnome - [Full, Lite, Minimal] - [gnome, gnome-extra]
Or a second solution where the install type are dedicated to gnome and optionally a second choice for gnome-extra
Install - Desktop Environement - Gnome - [gnome, gnome-extra] - [Full, Lite, Minimal]

If you not sure how to implement it, I can create a branch with the layout but you need to help me to choose in the two menu layout (or propose an other one) and to update the lite version with your actual packages. And optionaly, make a minimal version.

**Comment by MatMoul** [comment]
@Arch-Lover What the best?
Install - Desktop Environement - Gnome - [Full, Lite, Minimal] - [gnome, gnome-extra]
Install - Desktop Environement - Gnome - [gnome, gnome-extra] - [Full, Lite, Minimal]

**Comment by Arch-Lover** [comment]
i think "Install - Desktop Environement - Gnome - [Full, Lite, Minimal] - [gnome, gnome-extra]" is better.
cause you first chose you need full version or lite or minimal and than if you think there should be added some special packages, you just pick it up from gnome main group or gnome extra group
this is my idea.

**Comment by MatMoul** [comment]
@Arch-Lover Ok, I'll follow your idea...

**Comment by MatMoul** [comment]
@Arch-Lover I've just pushed a new branch named gnome with the layout...
Don't miss to remove () on your name on the Install Desktop Menu...

**Comment by MatMoul** [comment]
@Arch-Lover Sorry but with no feedback, I close the PR.

**Pull request closed without merging**
