### PR TITLE
Adding Quodlibet

### PR DESCRIPTION
**Pull request by FredBezies**
and adding Quodlibet.

### CODE REVIEW

**Comment by MatMoul** [comment]
Don't touch on my amarok ;-p
It has just been rewritten for QT5 (Same state as the migration of kde4 to plasma5 one year ago...)
It would be best to not mix the additions and deletion...

**Comment by MatMoul** [comment]
Excellent (AUR packages after official packages)

**Comment by FredBezies** [comment]
Just looked at your code. Better, I think and I hope.

**Comment by MatMoul** [comment]
I've just saw that you have typed Amarok...
I've corrected it...
Don't miss to test your change with `archdi -t FredBezies patch-x`

**Comment by FredBezies** [comment]
I will test them... I tried to follow your code the best I can. I'll test them ASAP. By the way, sorry for the little mistake!

**Comment by MatMoul** [comment]
No problem, it's not a criticism and I appreciate your contributions ...
As an author, my goal is to guide you ...

**Comment by FredBezies** [comment]
No problem at all. I looked at every single applications part and see what's still alive, what's dead, what can be added. Your tool is already really complete. Just a little cleanup, so :)

**Pull request merged**
